FROM registry.redhat.io/ubi9/python-312@sha256:558341c02c51ee12820185b203edaa953f18d1c2ac4426947547edd9cea44ff0

WORKDIR /usr/local/src/kfp/components

COPY . .

RUN pip install --no-cache-dir -e ".[remote]"

LABEL com.redhat.component="odh-trustyai-ragas-lls-provider-dsp-rhel9" \
      name="rhoai/odh-trustyai-ragas-lls-provider-dsp-rhel9" \
      description="odh-trustyai-ragas-lls-provider-dsp" \
      summary="odh-trustyai-ragas-lls-provider-dsp" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-trustyai-ragas-lls-provider-dsp" \
      io.k8s.description="odh-trustyai-ragas-lls-provider-dsp" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
